## Q -Session Question

# Q-1 > Create a 3x3 matrix with values ranging from 0 to 8.

In [142]:
import pandas as pd
import numpy as np
from scipy import stats

In [20]:
# Creating a 3*3 Matrix
arr1 = np.arange(0,9,1,int).reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Q-2 Given a 2D array, extract all the elements that are greater than a specified value (specified_value = 5).

In [45]:
arr_2d = np.array([[11, 12, 5, 2], [15, 6,10,5], [10, 8, 12, 5], [12,15,8,6]])
print(arr_2d[arr_2d > 5])


[11 12 15  6 10 10  8 12 12 15  8  6]


# Q-3 Create a 5x5 identity matrix.(np.eye)

In [25]:
arr_iden = np.eye(5,5)
print(arr_iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Q-4 Swap the first and last rows of a 2D array.

In [52]:
print("The Orignal Array")
print(arr_2d)
print("After Swap")
arr_2d[[0,3]] = arr_2d[[3,0]]
print(arr_2d)

The Orignal Array
[[12 15  8  6]
 [15  6 10  5]
 [10  8 12  5]
 [11 12  5  2]]
After Swap
[[11 12  5  2]
 [15  6 10  5]
 [10  8 12  5]
 [12 15  8  6]]


# Given a 1D array, find the indices of the minimum and maximum values (np.argmin/np.argmax).

In [80]:
arr_3 = np.array([4,9,1,11,20,19,14])
print("The Minimum indices")
mi = np.argmin(arr_3)
print(mi)
print("The Maximum indices")
ma = np.argmax(arr_3)
print(ma)

The Minimum indices
2
The Maximum indices
4


# Sort a given 1D array in ascending and descending order.

In [84]:
print("The orignal")
print(arr_3)
print("The ascending Order")
asce = arr_3.sort() 
print (arr_3)



The orignal
[ 4  9  1 11 20 19 14]
The ascending Order
[ 1  4  9 11 14 19 20]


# Q - Numpy Question

# Creating array till 10.

In [92]:

arr_ten = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_ten)


[ 1  2  3  4  5  6  7  8  9 10]


# Array Operations: Perform element-wise addition, subtraction, multiplication, and division on two NumPy arrays.

In [102]:
ha_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ha_2 = np.array([[7,16,3],[3,5,9],[12,3,1]])
subtr = np.subtract(ha_1,ha_2)
print ("The result is - \n", subtr)
Addi = np.add(ha_1,ha_2)
print ("The result is - \n", Addi)
Mul = np.multiply(ha_1,ha_2)
print ("The result is - \n", Mul)
Div = np.divide(ha_1,ha_2)
print ("The result is -\n", Div)

The result is - 
 [[ -6 -14   0]
 [  1   0  -3]
 [ -5   5   8]]
The result is - 
 [[ 8 18  6]
 [ 7 10 15]
 [19 11 10]]
The result is - 
 [[ 7 32  9]
 [12 25 54]
 [84 24  9]]
The result is -
 [[0.14285714 0.125      1.        ]
 [1.33333333 1.         0.66666667]
 [0.58333333 2.66666667 9.        ]]


# Array Slicing: Extract the first three elements from a NumPy array.

In [109]:
print ("the orignal array")
print(arr_ten)
print("The first three element")
print(arr_ten[0:3])

the orignal array
[ 1  2  3  4  5  6  7  8  9 10]
The first three element
[1 2 3]


# Array Reshaping: Reshape a 1D NumPy array into a 2D array with 2 rows and 3 columns.

In [121]:
arr_six = np.array([1,2,3,4,5,6])
arr_six.reshape(2,3)


array([[1, 2, 3],
       [4, 5, 6]])

# Array Aggregation: Calculate the mean, median, and standard deviation of a NumPy array

In [136]:
# Mean
Mean_of_array = np.mean(arr_six)
print(Mean_of_array)

3.5


In [138]:
# Median 
Median_of_array = np.median(arr_six)
print(Median_of_array)

3.5


In [144]:
ar = np.array([5,3,2,4,5,6,7,8,9,9,8,7,7,6])
Mode_of_array = stats.mode(ar)
print(Mode_of_array)

ModeResult(mode=7, count=3)


# PANDA QUESTIONS

In [ ]:


DataFrame Operations: Add a new column to an existing DataFrame. Perform element-wise operations between two columns.

Data Selection: Select rows based on a condition. Select specific columns from a DataFrame.

Data Aggregation: Group the data in a DataFrame based on a categorical column and calculate the mean of each group.

Data Cleaning: Handle missing values by either removing or replacing them with appropriate values.

# DataFrame Creation: Create a pandas DataFrame from a dictionary of lists, where each list represents a column.

In [302]:
# cREATE A DATA
data = {'Name': ['ALICE', 'Bob','Cyan', 'Bob','Kayne','kill','rao', 'ram'],
       'Age' : [23,23,25,26,27,22,23,23],
       'City' : ['Newyork','Chicago','Houston','Pheonix','Los Angeles','UK','India','WI']}
print(data)
df = pd.DataFrame(data)
print(df)

{'Name': ['ALICE', 'Bob', 'Cyan', 'Bob', 'Kayne', 'kill', 'rao', 'ram'], 'Age': [23, 23, 25, 26, 27, 22, 23, 23], 'City': ['Newyork', 'Chicago', 'Houston', 'Pheonix', 'Los Angeles', 'UK', 'India', 'WI']}
    Name  Age         City
0  ALICE   23      Newyork
1    Bob   23      Chicago
2   Cyan   25      Houston
3    Bob   26      Pheonix
4  Kayne   27  Los Angeles
5   kill   22           UK
6    rao   23        India
7    ram   23           WI


# DataFrame Operations: Add a new column to an existing DataFrame. Perform element-wise operations between two columns.

In [305]:
df.insert(2, "Earnings", [21000, 23500, 24999, 29000,31000,40000,35090,50000], True)

In [307]:
df["Earning_by_month"] = df["Earnings"] / 12

In [309]:
print(df)

    Name  Age  Earnings         City  Earning_by_month
0  ALICE   23     21000      Newyork       1750.000000
1    Bob   23     23500      Chicago       1958.333333
2   Cyan   25     24999      Houston       2083.250000
3    Bob   26     29000      Pheonix       2416.666667
4  Kayne   27     31000  Los Angeles       2583.333333
5   kill   22     40000           UK       3333.333333
6    rao   23     35090        India       2924.166667
7    ram   23     50000           WI       4166.666667


# Data Selection: Select rows based on a condition. Select specific columns from a DataFrame. 

In [312]:
filtered_df = df[df['Age'] > 22]

In [314]:
print(filtered_df)

    Name  Age  Earnings         City  Earning_by_month
0  ALICE   23     21000      Newyork       1750.000000
1    Bob   23     23500      Chicago       1958.333333
2   Cyan   25     24999      Houston       2083.250000
3    Bob   26     29000      Pheonix       2416.666667
4  Kayne   27     31000  Los Angeles       2583.333333
6    rao   23     35090        India       2924.166667
7    ram   23     50000           WI       4166.666667


# Data Aggregation: Group the data in a DataFrame based on a categorical column and calculate the mean of each group.

In [317]:
filtta = df.groupby(["Name","City"])

In [319]:
df_group = filtta[["Age"]]
df_group.count()

Age
Name  City            
ALICE Newyork        1
Bob   Chicago        1
      Pheonix        1
Cyan  Houston        1
Kayne Los Angeles    1
kill  UK             1
ram   WI             1
rao   India          1

In [323]:
df_age = df.groupby(['Age','Earnings'])

In [325]:
df_age.count()


Name  City  Earning_by_month
Age Earnings                              
22  40000        1     1                 1
23  21000        1     1                 1
    23500        1     1                 1
    35090        1     1                 1
    50000        1     1                 1
25  24999        1     1                 1
26  29000        1     1                 1
27  31000        1     1                 1

In [327]:
grouped = df_age.sum()
print(grouped)

               Name         City  Earning_by_month
Age Earnings                                      
22  40000      kill           UK       3333.333333
23  21000     ALICE      Newyork       1750.000000
    23500       Bob      Chicago       1958.333333
    35090       rao        India       2924.166667
    50000       ram           WI       4166.666667
25  24999      Cyan      Houston       2083.250000
26  29000       Bob      Pheonix       2416.666667
27  31000     Kayne  Los Angeles       2583.333333


In [339]:
f_f = df['Name']=='Bob'
me = df[f_f]['Age'].mean()
print(me)

24.5


In [343]:

ne = df[f_f]['Earnings'].mean()
print(ne)

26250.0


# Data Cleaning: Handle missing values by either removing or replacing them with appropriate values.

In [346]:
print(df.isnull().sum())

Name                0
Age                 0
Earnings            0
City                0
Earning_by_month    0
dtype: int64


In [352]:
df_ww = df.drop(['Age'],axis=1)
df_ww.isnull().sum()

Name                0
Earnings            0
City                0
Earning_by_month    0
dtype: int64

In [356]:
print(df_ww)

    Name  Earnings         City  Earning_by_month
0  ALICE     21000      Newyork       1750.000000
1    Bob     23500      Chicago       1958.333333
2   Cyan     24999      Houston       2083.250000
3    Bob     29000      Pheonix       2416.666667
4  Kayne     31000  Los Angeles       2583.333333
5   kill     40000           UK       3333.333333
6    rao     35090        India       2924.166667
7    ram     50000           WI       4166.666667
